name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  call-workflow-deploy:
    name: deploy
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
